/* add at least 3 records into each table */
INSERT INTO [dbo].[Products] ([ID], [Name], [Price]) VALUES (1, "Macbook", 1000);
INSERT INTO [dbo].[Products] ([ID], [Name], [Price]) VALUES (2, "PC", 800);
INSERT INTO [dbo].[Products] ([ID], [Name], [Price]) VALUES (3, "TV", 500);

INSERT INTO [dbo].[Orders] ([ID], [ProductID], [CustomerID]) VALUES (1, 1, 1);
INSERT INTO [dbo].[Orders] ([ID], [ProductID], [CustomerID]) VALUES (2, 2, 2);
INSERT INTO [dbo].[Orders] ([ID], [ProductID], [CustomerID]) VALUES (3, 3, 3);

INSERT INTO [dbo].[Customers] ([ID], [Firstname], [Lastname], [CardNumber]) VALUES (1, "Angelica", "Velez", 123456789);
INSERT INTO [dbo].[Customers] ([ID], [Firstname], [Lastname], [CardNumber]) VALUES (2, "Nick", "Escalona", 987654321);
INSERT INTO [dbo].[Customers] ([ID], [Firstname], [Lastname], [CardNumber]) VALUES (3, "Mark", "Moore", 345678912);


/* add product iphone priced at $200 */
INSERT INTO [dbo].[Products] ([ID], [Name], [Price]) VALUES (4, "iPhone", 200);

/* add customer tina smith */
INSERT INTO [dbo].[Customers] ([ID], [Firstname], [Lastname], [CardNumber]) VALUES (2, "Tina", "Smith", 567891234);

/* create order for "tina smith bought an iphone" */
INSERT INTO [dbo].[Orders] ([ID], [ProductID], [CustomerID]) VALUES (1, 4, 4); 

/* report all orders by tina smith */
SELECT * FROM Orders WHERE CustomerID = 4;

/* report all revenue generated by sales of iphone */
SELECT SUM(Price)
FROM Products
JOIN Orders ON Products
WHERE ProductID = 4;

/* increase the price of iphone to $250 */
UPDATE Products
SET Price = 250
WHERE ID = 4;